sequenceDiagram

participant User
participant Visualizer Client
participant ESDA Records Server
participant Backend Supplying Data

User ->> Visualizer Client: load configuration
activate Visualizer Client
Visualizer Client ->> ESDA Records Server: RequestModelsMeta
activate ESDA Records Server
ESDA Records Server ->> Backend Supplying Data: list data sources
activate Backend Supplying Data
Backend Supplying Data -->> ESDA Records Server: metadata for sources
deactivate Backend Supplying Data
ESDA Records Server --x Visualizer Client: ModelMetaList
deactivate ESDA Records Server
Visualizer Client -->> User: show list of models
deactivate Visualizer Client

User ->> Visualizer Client: select model to display
activate Visualizer Client
Visualizer Client ->> ESDA Records Server: RequestRecordsData
activate ESDA Records Server
ESDA Records Server ->> Backend Supplying Data: get data from source
activate Backend Supplying Data
Backend Supplying Data -->> ESDA Records Server: available data from source
deactivate Backend Supplying Data
ESDA Records Server --x Visualizer Client: RecordData
Visualizer Client --x User: show visualization

loop poll source for new data
  ESDA Records Server ->> Backend Supplying Data: get data from source
  activate Backend Supplying Data
  Backend Supplying Data -->> ESDA Records Server: new data from source
  deactivate Backend Supplying Data
  ESDA Records Server --x Visualizer Client: RecordData
  Visualizer Client --x User: update visualization
end

User ->> Visualizer Client: stop updates
Visualizer Client ->> ESDA Records Server: RequestCancel
deactivate ESDA Records Server
deactivate Visualizer Client
